# Data quality scan: buildings with `HtTot` (Oslo + Drammen)

Goal: decide, from facts, which buildings go into the silver/gold layers for predicting `HtTot` from weather + time.
Run the cells top to bottom. Each step ends with a **Decision** note so you can write down your thresholds before preprocessing.

Only the header rows are read in steps 1-2. From step 3 the data is loaded building by building.

In [12]:
from pathlib import Path
import pandas as pd

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 50)
pd.set_option("display.max_rows", 200)

ROOT = Path("..") / "datasets"
SOURCES = {
    "oslo": ROOT / "COFACTOR-SBHUB-Oslo" / "Dataset_buildings_csv_files",
    "drammen": ROOT / "Cofactor_Drammen_Buildings_45_v3",
}
WEATHER = ["Tout", "SolGlob", "WindSpd", "WindDir", "RH"]

## 1. Read only the metadata + column row of every file
Line 1 is `Header_line;N`, and `N` is the line number of the column row. Lines 2 up to the blank line are `key;value` metadata.

In [13]:
def read_head(path):
    """Return (meta dict, column list, header line number) without reading the data rows."""
    meta, cols = {}, None
    with open(path, encoding="utf-8", errors="replace") as f:
        n = int(f.readline().strip().split(";")[1])
        for i in range(2, n + 1):
            line = f.readline().rstrip("\r\n")
            if i == n:
                cols = line.split(";")
            elif ";" in line and line.split(";")[0]:
                k, v = line.split(";", 1)
                meta[k] = v
    return meta, cols, n

rows = []
for city, folder in SOURCES.items():
    for p in sorted(folder.glob("*.txt")):
        meta, cols, n = read_head(p)
        rows.append({"city": city, "file": p.name, "path": p, "header_line": n,
                     "cols": cols, **meta})
files = pd.DataFrame(rows)
try:
    files["building_id"] = files["building_id"].astype(int)
except ValueError as e:
    print("building_id is not a clean integer:", e)
    bad = files[~files["building_id"].astype(str).str.fullmatch(r"\d+")]
    print(f"\n{len(bad)} file(s) with a bad building_id:")
    print(bad[["city", "file", "building_id", "header_line"]].to_string())
    print("\nFirst rows of the dataframe:")
    print(files.head().to_string())
print(files.groupby("city").size())
files[["city", "file", "building_id", "header_line", "building_category", "year_of_construction", "floor_area"]].head()

city
drammen    45
oslo       48
dtype: int64

   city             file  building_id  header_line building_category year_of_construction floor_area
0  oslo  export_8091.txt         8091           19               Sch                 2004       6550
1  oslo  export_8092.txt         8092           18               Sch                 1970       7047
2  oslo  export_8093.txt         8093           17               Sch                 1965       9072
3  oslo  export_8094.txt         8094           18               Sch                  NaN      27479
4  oslo  export_8095.txt         8095           17               Sch                 1975       6066

## 2. Which buildings have `HtTot`?
Check: do all rows have a unique `building_id`, and how many buildings per city have `HtTot` in the header?

In [14]:
files["has_HtTot"] = files["cols"].apply(lambda c: "HtTot" in c)
files["has_HtDH"] = files["cols"].apply(lambda c: "HtDH" in c)
print("duplicate building_id:", files["building_id"].duplicated().sum())
print(files.groupby("city")[["has_HtTot", "has_HtDH"]].sum())
print("total with HtTot:", files["has_HtTot"].sum())

target = files[files["has_HtTot"]].reset_index(drop=True)
print("\nbuilding_category among target buildings:")
print(target.groupby(["city", "building_category"]).size())

duplicate building_id: 0
         has_HtTot  has_HtDH
city
drammen          5         3
oslo            33        29
total with HtTot: 38

building_category among target buildings:
city     building_category
drammen  Kdg                   2
         Nsh                   3
oslo     Sch                  33
dtype: int64

**Decision:** you counted about 37, my header scan gives 38 (33 Oslo + 5 Drammen). Step 4 will show whether one of them has an empty `HtTot`.

## 3. Common columns across the target buildings
Weather columns are expected everywhere. Check which columns are present in every target building and which are only in some.

In [15]:
from collections import Counter
cnt = Counter(c for cols in target["cols"] for c in cols)
common = pd.Series(cnt).sort_values(ascending=False).rename("n_buildings").to_frame()
common["share"] = (common["n_buildings"] / len(target)).round(2)
print(common)
print("\nin every target building:", common.index[common["n_buildings"] == len(target)].tolist())

           n_buildings  share
TimeStamp           38   1.00
HtTot               38   1.00
ElImp               38   1.00
Tout                38   1.00
WindSpd             38   1.00
SolGlob             38   1.00
WindDir             38   1.00
RH                  33   0.87
HtDH                29   0.76
HtDHW                8   0.21
HtHP                 7   0.18
ElHP                 7   0.18
ElBoil               6   0.16
ElHWH                5   0.13
ElPV                 3   0.08
ElExp                3   0.08
ElFan                2   0.05
HtBio                1   0.03
ElSpace              1   0.03
HtVent               1   0.03
ElLight              1   0.03
HtSpace              1   0.03
HtSnow               1   0.03
ClComf               1   0.03
ElEV                 1   0.03
ElDHW                1   0.03
ElSnow               1   0.03
HtOil                1   0.03

in every target building: ['TimeStamp', 'HtTot', 'ElImp', 'Tout', 'WindSpd', 'SolGlob', 'WindDir']

**Decision:** `RH` is expected to be missing in Drammen. Choose: drop `RH`, or keep it and fill/skip for Drammen.

## 4. Load each target building and build a per-building quality table
Timestamps are fixed UTC+1 all year (no DST), so the offset is stripped and times are kept naive, like in the earlier check notebook.
This cell reads the data of the target buildings only, one at a time, and keeps just a summary.

In [16]:
def load(row):
    df = pd.read_csv(row["path"], sep=";", skiprows=row["header_line"] - 1)
    raw_ts = df["TimeStamp"]
    offsets = raw_ts.str[-5:].unique().tolist()
    df["ts"] = pd.to_datetime(raw_ts.str[:19])
    df = df.set_index("ts").drop(columns="TimeStamp").sort_index()
    return df, offsets

def longest_run(mask):
    """Length of the longest run of True in a boolean Series."""
    grp = (~mask).cumsum()
    return int(mask.groupby(grp).sum().max()) if mask.any() else 0

summ = []
for _, r in target.iterrows():
    df, offsets = load(r)
    idx = df.index
    full = pd.date_range(idx.min(), idx.max(), freq="h")
    h = df["HtTot"]
    flat = h.eq(h.shift()) & h.gt(0)
    summ.append({
        "city": r["city"], "id": r["building_id"], "cat": r["building_category"],
        "rows": len(df), "start": idx.min().date(), "end": idx.max().date(),
        "years": round((idx.max() - idx.min()).days / 365.25, 2),
        "missing_hours": len(full.difference(idx)), "dup_ts": int(idx.duplicated().sum()),
        "offsets": ",".join(offsets),
        "Ht_nan_%": round(h.isna().mean() * 100, 1),
        "Ht_zero_%": round((h == 0).mean() * 100, 1),
        "Ht_neg": int((h < 0).sum()),
        "Ht_flat_%": round(flat.mean() * 100, 1),
        "Ht_longest_nan_h": longest_run(h.isna()),
        "Ht_max": h.max(),
        "Tout_nan_%": round(df["Tout"].isna().mean() * 100, 1),
        "Tout_sentinel": int((df["Tout"] < -100).sum()),
        "Sol_neg": int((df["SolGlob"] < 0).sum()),
        "RH_present": "RH" in df.columns,
        "HtTot==HtDH": bool("HtDH" in df.columns and (df["HtTot"].dropna() == df["HtDH"].reindex(df["HtTot"].dropna().index)).mean() > 0.99),
    })
quality = pd.DataFrame(summ).sort_values(["city", "id"]).reset_index(drop=True)
quality

,city,id,cat,rows,start,end,years,missing_hours,dup_ts,offsets,Ht_nan_%,Ht_zero_%,Ht_neg,Ht_flat_%,Ht_longest_nan_h,Ht_max,Tout_nan_%,Tout_sentinel,Sol_neg,RH_present,HtTot==HtDH
0,drammen,6409,Kdg,35064,2018-01-01,2021-12-31,4.00,0,0,+0100,1.1,0.1,0,18.8,264,9.040000e+04,0.2,0,406,False,False
1,drammen,6412,Nsh,35064,2018-01-01,2021-12-31,4.00,0,0,+0100,0.3,8.1,0,36.1,48,1.850530e+09,0.2,0,386,False,False
2,drammen,6429,Kdg,36708,2018-01-01,2022-03-10,4.19,0,0,+0100,50.0,0.0,0,8.1,3312,9.900000e+04,0.3,0,430,False,True
3,drammen,6436,Nsh,36341,2018-01-01,2022-02-23,4.15,0,0,+0100,4.9,29.5,0,12.7,48,3.900000e+05,0.3,0,407,False,True
4,drammen,6442,Nsh,36348,2018-01-01,2022-02-23,4.15,0,0,+0100,0.7,25.1,0,30.5,168,1.700000e+05,0.3,0,407,False,False
5,oslo,8091,Sch,24600,2021-01-01,2023-10-22,2.80,0,0,+0100,0.0,2.8,0,9.5,0,4.280000e+05,0.0,0,945,True,True
6,oslo,8092,Sch,85978,2014-01-01,2023-10-23,9.81,0,0,+0100,0.0,18.4,0,30.2,1,4.700000e+05,0.0,1,3770,True,False
7,oslo,8093,Sch,8809,2019-03-05,2020-03-06,1.00,0,0,+0100,0.0,1.3,0,16.9,0,4.256000e+05,0.0,1,386,True,False
8,oslo,8094,Sch,35088,2016-01-01,2020-01-01,4.00,0,0,+0100,0.0,28.5,0,29.0,0,1.700000e+06,0.0,0,1595,True,True
9,oslo,8095,Sch,50914,2018-01-01,2023-10-23,5.81,0,0,+0100,0.0,26.6,0,13.1,0,4.356042e+05,0.0,1,2075,True,False
10,oslo,8096,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,14.0,0,33.5,0,4.900000e+05,0.0,1,4272,True,True
11,oslo,8102,Sch,33391,2020-01-01,2023-10-23,3.81,0,0,+0100,0.0,7.6,0,21.2,1,9.300000e+05,0.0,1,1310,True,True
12,oslo,8103,Sch,68448,2016-01-01,2023-10-22,7.81,0,0,+0100,0.0,2.4,0,17.9,0,6.200000e+05,0.0,1,2872,True,True
13,oslo,8104,Sch,42154,2019-01-01,2023-10-23,4.81,0,0,+0100,0.0,8.7,0,33.6,10,3.100000e+05,0.0,1,1664,True,True
14,oslo,8105,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,18.5,0,21.7,0,6.400000e+05,0.0,1,4292,True,True
15,oslo,8106,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,73.1,1.4,0,2.4,70871,3.930000e+05,0.0,1,4350,True,True
16,oslo,8107,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,8.9,0,29.6,0,5.800000e+05,0.0,1,4290,True,True
17,oslo,8108,Sch,77459,2014-12-22,2023-10-23,8.84,0,0,+0100,0.0,16.6,0,30.0,4,3.600000e+05,0.0,1,3336,True,True
18,oslo,8109,Sch,45705,2018-08-06,2023-10-23,5.21,0,0,+0100,0.0,16.1,0,23.0,0,4.200000e+05,0.0,1,1819,True,False
19,oslo,8110,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,20.2,0,25.0,0,4.800000e+05,0.0,1,4252,True,True
20,oslo,8113,Sch,84744,2012-10-01,2022-06-01,9.66,0,0,+0100,0.0,20.3,0,25.8,0,5.300000e+05,0.0,1,3834,True,True
21,oslo,8114,Sch,96946,2012-10-01,2023-10-23,11.06,0,0,+0100,0.0,3.7,0,14.8,0,1.370000e+06,0.0,1,4273,True,True
22,oslo,8116,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,3.9,0,23.8,1,8.400000e+05,0.0,1,4308,True,True
23,oslo,8117,Sch,32651,2020-02-01,2023-10-23,3.72,0,0,+0100,1.4,19.7,0,31.3,469,3.400000e+05,0.0,1,1241,True,False
24,oslo,8119,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,6.1,0,30.0,0,6.800000e+05,0.0,1,4350,True,True
25,oslo,8120,Sch,46056,2012-10-01,2018-01-01,5.25,0,0,+0100,0.0,45.1,0,28.0,0,7.010000e+05,0.0,0,2242,True,True
26,oslo,8121,Sch,77215,2015-01-01,2023-10-23,8.81,0,0,+0100,0.0,23.8,0,26.2,1,3.000000e+05,0.0,1,3299,True,True
27,oslo,8122,Sch,85980,2014-01-01,2023-10-23,9.81,0,0,+0100,0.0,8.4,0,27.4,12,5.500000e+05,0.0,1,3747,True,True
28,oslo,8124,Sch,10297,2017-01-01,2018-03-06,1.17,0,0,+0100,0.0,16.3,0,21.2,1,1.810000e+06,0.0,0,515,True,True
29,oslo,8125,Sch,10945,2012-10-01,2013-12-31,1.25,0,0,+0100,0.0,24.1,0,23.0,0,5.200000e+05,0.0,0,529,True,True
30,oslo,8126,Sch,96944,2012-10-01,2023-10-23,11.06,0,0,+0100,0.0,3.5,0,27.3,8,5.800000e+05,0.0,1,4297,True,True
31,oslo,8127,Sch,24609,2021-01-01,2023-10-23,2.81,0,0,+0100,0.0,18.4,0,18.9,1,6.077000e+05,0.0,0,950,True,False
32,oslo,8128,Sch,76232,2015-02-11,2023-10-23,8.70,0,0,+0100,0.0,27.4,0,12.8,4,5.700000e+05,0.0,1,3272,True,True
33,oslo,8131,Sch,35592,2019-10-01,2023-10-22,4.06,0,0,+0100,0.0,2.9,0,22.0,0,3.260000e+05,0.0,1,1400,True,True
34,oslo,8132,Sch,96936,2012-10-01,2023-10-22,11.06,0,0,+0100,0.0,11.1,0,31.9,1,1.130000e+06,0.0,1,4292,True,True
35,oslo,8133,Sch,49680,2012-10-01,2018-06-01,5.66,0,0,+0100,0.0,11.4,0,25.7,0,1.060000e+06,0.0,0,2376,True,True
36,oslo,8135,Sch,48480,2018-04-16,2023-10-26,5.53,0,0,+0100,0.0,4.2,0,20.5,0,5.100000e+05,0.0,1,1917,True,True
37,oslo,8137,Sch,46056,2012-10-01,2018-01-01,5.25,0,0,+0100,0.0,11.1,0,21.4,0,9.000000e+05,0.0,0,2259,True,True

Read the table column by column:
- `rows`, `years`: how much data per building.
- `missing_hours`, `dup_ts`: gaps and duplicate timestamps in the time index.
- `offsets`: should be only `+0100`. Anything else means the fixed-UTC+1 assumption is wrong for that file.
- `Ht_nan_%`, `Ht_longest_nan_h`: how empty the target is, and the longest hole.
- `Ht_zero_%`, `Ht_neg`, `Ht_flat_%`: suspicious target values (zeros, negatives, the same value repeated).
- `Tout_sentinel`, `Sol_neg`: known weather problems (-273.15 sentinel, negative solar).
- `HtTot==HtDH`: whether the target is just a copy of district heating (so `HtDH` must never be a feature).

## 5. Summary statistics over all target buildings

In [17]:
print(quality.describe().T[["min", "25%", "50%", "75%", "max"]].round(2))
print("\nbuildings with non-+0100 offsets:", (quality["offsets"] != "+0100").sum())
print("buildings with any duplicate timestamps:", (quality["dup_ts"] > 0).sum())
print("buildings where HtTot is a copy of HtDH:", quality["HtTot==HtDH"].sum())
print("total rows:", quality["rows"].sum())

                      min        25%        50%        75%           max
id                 6409.0    8095.25    8109.50    8123.50  8.137000e+03
rows               8809.0   35214.00   49080.00   94197.00  9.694600e+04
years                 1.0       4.01       5.60      10.75  1.106000e+01
missing_hours         0.0       0.00       0.00       0.00  0.000000e+00
dup_ts                0.0       0.00       0.00       0.00  0.000000e+00
Ht_nan_%              0.0       0.00       0.00       0.00  7.310000e+01
Ht_zero_%             0.0       3.98      11.25      20.08  4.510000e+01
Ht_neg                0.0       0.00       0.00       0.00  0.000000e+00
Ht_flat_%             2.4      18.82      23.40      29.45  3.610000e+01
Ht_longest_nan_h      0.0       0.00       0.50       7.00  7.087100e+04
Ht_max            90400.0  399750.00  525000.00  695750.00  1.850530e+09
Tout_nan_%            0.0       0.00       0.00       0.00  3.000000e-01
Tout_sentinel         0.0       0.00       1.00       1.00  1.000000e+00
Sol_neg             386.0    1022.75    2250.50    4147.50  4.350000e+03

buildings with non-+0100 offsets: 0
buildings with any duplicate timestamps: 0
buildings where HtTot is a copy of HtDH: 29
total rows: 2249986

## 6. Flag problem buildings
Change the thresholds to your own choices, then look at which buildings fall out.

In [18]:
# EDIT THESE after reading steps 4-5
MAX_HT_NAN_PCT = 20       # target mostly empty
MAX_LONGEST_NAN_H = 24 * 30  # one hole longer than this many hours
MAX_HT_ZERO_PCT = 20      # target mostly zero
MAX_HT_FLAT_PCT = 20      # target mostly repeated values
MIN_YEARS = 1.0           # at least a full seasonal cycle

q = quality.copy()
q["flag_nan"] = q["Ht_nan_%"] > MAX_HT_NAN_PCT
q["flag_hole"] = q["Ht_longest_nan_h"] > MAX_LONGEST_NAN_H
q["flag_zero"] = q["Ht_zero_%"] > MAX_HT_ZERO_PCT
q["flag_flat"] = q["Ht_flat_%"] > MAX_HT_FLAT_PCT
q["flag_short"] = q["years"] < MIN_YEARS
flag_cols = [c for c in q.columns if c.startswith("flag_")]
q["n_flags"] = q[flag_cols].sum(axis=1)
print("flagged:", (q["n_flags"] > 0).sum(), "of", len(q))
q[q["n_flags"] > 0][["city", "id", "years", "Ht_nan_%", "Ht_longest_nan_h", "Ht_zero_%", "Ht_flat_%"] + flag_cols]

flagged: 32 of 38

       city    id  years  Ht_nan_%  Ht_longest_nan_h  Ht_zero_%  Ht_flat_%  flag_nan  flag_hole  flag_zero  flag_flat  flag_short
1   drammen  6412   4.00       0.3                48        8.1       36.1     False      False      False       True       False
2   drammen  6429   4.19      50.0              3312        0.0        8.1      True       True      False      False       False
3   drammen  6436   4.15       4.9                48       29.5       12.7     False      False       True      False       False
4   drammen  6442   4.15       0.7               168       25.1       30.5     False      False       True       True       False
6      oslo  8092   9.81       0.0                 1       18.4       30.2     False      False      False       True       False
8      oslo  8094   4.00       0.0                 0       28.5       29.0     False      False       True       True       False
9      oslo  8095   5.81       0.0                 0       26.6       13.1     False      False       True      False       False
10     oslo  8096  11.06       0.0                 0       14.0       33.5     False      False      False       True       False
11     oslo  8102   3.81       0.0                 1        7.6       21.2     False      False      False       True       False
13     oslo  8104   4.81       0.0                10        8.7       33.6     False      False      False       True       False
14     oslo  8105  11.06       0.0                 0       18.5       21.7     False      False      False       True       False
15     oslo  8106  11.06      73.1             70871        1.4        2.4      True       True      False      False       False
16     oslo  8107  11.06       0.0                 0        8.9       29.6     False      False      False       True       False
17     oslo  8108   8.84       0.0                 4       16.6       30.0     False      False      False       True       False
18     oslo  8109   5.21       0.0                 0       16.1       23.0     False      False      False       True       False
19     oslo  8110  11.06       0.0                 0       20.2       25.0     False      False       True       True       False
20     oslo  8113   9.66       0.0                 0       20.3       25.8     False      False       True       True       False
22     oslo  8116  11.06       0.0                 1        3.9       23.8     False      False      False       True       False
23     oslo  8117   3.72       1.4               469       19.7       31.3     False      False      False       True       False
24     oslo  8119  11.06       0.0                 0        6.1       30.0     False      False      False       True       False
25     oslo  8120   5.25       0.0                 0       45.1       28.0     False      False       True       True       False
26     oslo  8121   8.81       0.0                 1       23.8       26.2     False      False       True       True       False
27     oslo  8122   9.81       0.0                12        8.4       27.4     False      False      False       True       False
28     oslo  8124   1.17       0.0                 1       16.3       21.2     False      False      False       True       False
29     oslo  8125   1.25       0.0                 0       24.1       23.0     False      False       True       True       False
30     oslo  8126  11.06       0.0                 8        3.5       27.3     False      False      False       True       False
32     oslo  8128   8.70       0.0                 4       27.4       12.8     False      False       True      False       False
33     oslo  8131   4.06       0.0                 0        2.9       22.0     False      False      False       True       False
34     oslo  8132  11.06       0.0                 1       11.1       31.9     False      False      False       True       False
35     oslo  8133   5.66       0.0                 0       11.4       25.7     False      False      False       True       False
36     oslo  8135   5.53       0.0                 0        4.2       20.5     False      False      False       True       False
37     oslo  8137   5.25       0.0                 0       11.1       21.4     False      False      False       True       False

## 7. Look at the target by eye
Monthly total `HtTot` (MWh) per building. A building should show high winter and low summer values. Odd shapes (flat, all zero, big jumps) deserve a closer look.

In [19]:
monthly = {}
for _, r in target.iterrows():
    df, _ = load(r)
    monthly[f'{r["city"]}-{r["building_id"]}'] = (df["HtTot"].resample("MS").sum(min_count=1) / 1e6).round(1)
pd.DataFrame(monthly).T

ts,2012-10-01,2012-11-01,2012-12-01,2013-01-01,2013-02-01,2013-03-01,2013-04-01,2013-05-01,2013-06-01,2013-07-01,2013-08-01,2013-09-01,2013-10-01,2013-11-01,2013-12-01,2014-01-01,2014-02-01,2014-03-01,2014-04-01,2014-05-01,2014-06-01,2014-07-01,2014-08-01,2014-09-01,2014-10-01,...,2021-10-01,2021-11-01,2021-12-01,2022-01-01,2022-02-01,2022-03-01,2022-04-01,2022-05-01,2022-06-01,2022-07-01,2022-08-01,2022-09-01,2022-10-01,2022-11-01,2022-12-01,2023-01-01,2023-02-01,2023-03-01,2023-04-01,2023-05-01,2023-06-01,2023-07-01,2023-08-01,2023-09-01,2023-10-01
oslo-8091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.7,79.6,111.7,87.3,77.3,72.0,56.0,34.0,9.4,5.5,8.8,26.1,40.3,58.9,105.6,85.6,69.7,99.4,60.9,32.6,8.0,10.5,12.3,22.9,41.5
oslo-8092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.1,78.9,66.2,48.1,27.6,8.1,1.9,9.0,20.8,48.6,...,23.5,48.6,66.1,61.8,48.9,46.7,26.0,13.7,6.2,4.0,3.2,14.3,27.6,41.9,72.7,68.0,50.1,58.6,32.8,18.9,3.6,1.1,4.1,12.7,22.9
oslo-8093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.1,49.0,68.0,62.2,54.2,53.2,34.4,19.3,8.0,4.6,6.1,21.4,32.2,46.0,62.9,55.5,42.6,51.5,32.1,19.4,3.9,7.8,8.6,10.6,20.7
oslo-8096,90.0,100.4,158.6,155.8,117.2,113.3,62.4,22.8,10.7,1.1,1.4,29.1,54.0,98.9,120.4,132.1,107.5,117.1,74.0,42.4,8.2,7.4,10.5,22.2,49.0,...,41.4,82.4,120.5,117.0,90.7,76.4,46.8,21.0,5.9,0.0,0.2,11.5,36.3,67.3,117.9,108.0,84.5,95.4,53.2,27.5,4.8,4.3,8.0,7.4,24.6
oslo-8102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.5,157.2,176.6,145.6,106.4,125.9,77.3,48.8,18.7,13.2,16.1,54.1,79.1,142.8,243.6,226.3,183.8,224.7,78.2,32.8,11.3,11.9,14.9,23.5,41.2
oslo-8103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.7,150.7,174.6,155.1,118.5,106.6,65.2,34.7,10.7,5.5,10.9,33.5,62.2,94.0,157.4,142.2,108.0,124.6,61.1,27.8,9.2,11.3,14.8,20.5,42.4
oslo-8104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.2,49.8,71.0,62.6,52.6,48.8,32.4,17.0,5.2,3.6,11.3,22.3,32.0,44.7,69.6,64.6,51.4,60.0,31.1,16.5,4.5,4.2,11.8,17.0,23.2
oslo-8105,91.7,113.0,209.8,206.8,159.2,152.1,81.7,27.6,11.0,4.0,5.9,27.5,62.6,105.8,122.7,185.4,115.2,91.4,41.7,20.6,5.3,2.2,5.6,13.9,44.6,...,48.4,85.1,136.2,112.7,97.7,98.8,44.8,18.8,5.8,3.2,3.5,17.8,43.3,72.8,133.7,119.7,88.2,102.7,45.5,17.5,4.2,3.6,4.6,10.4,31.8
oslo-8106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.7,72.4,103.7,90.2,77.4,71.5,46.4,31.4,8.6,4.7,6.4,26.1,44.0,65.8,103.9,93.6,73.1,83.6,45.3,21.2,4.6,5.9,8.3,19.1,33.5
oslo-8107,56.2,71.8,103.1,110.7,103.3,86.4,49.6,17.1,6.1,5.7,6.4,32.6,114.0,156.1,171.5,183.2,156.9,180.2,112.0,66.3,16.5,0.0,8.9,16.8,52.9,...,42.1,67.8,87.4,86.4,72.1,72.6,44.8,23.6,8.8,4.8,7.2,27.8,46.8,60.9,91.4,86.9,68.8,81.4,45.3,25.0,6.0,11.7,17.4,20.5,32.0
oslo-8108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.3,62.5,83.2,76.0,60.4,58.9,33.4,11.8,4.2,2.6,3.0,14.2,37.7,50.3,80.2,79.7,59.0,71.6,35.9,20.4,5.1,2.6,4.3,9.8,24.2
oslo-8109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,35.0,60.3,44.7,40.8,33.2,21.4,12.1,8.0,7.1,9.0,17.0,25.6,36.2,42.8,30.4,22.2,26.3,10.6,5.9,4.8,2.9,4.2,7.9,17.5
oslo-8110,53.1,60.6,92.8,95.0,79.1,78.9,51.5,19.6,6.4,2.7,5.4,22.1,44.8,64.3,71.9,89.9,67.7,61.8,47.4,23.0,5.3,2.9,16.2,39.1,97.0,...,39.5,68.6,101.8,87.9,58.1,79.1,39.7,18.5,2.2,1.6,3.5,15.5,36.4,55.0,84.9,87.6,63.9,84.0,38.8,20.2,4.0,4.9,7.0,13.0,23.4
oslo-8113,73.4,89.9,130.1,145.2,118.9,102.2,66.9,14.6,1.6,0.1,0.3,19.0,59.2,98.8,90.8,100.3,70.8,62.7,35.5,18.0,3.2,0.9,4.8,13.6,38.8,...,49.0,81.6,103.3,95.0,79.8,85.8,51.6,28.5,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8114,76.9,110.9,226.7,234.0,183.1,158.9,72.8,45.9,18.4,7.7,11.3,26.0,57.8,106.5,128.0,200.8,123.5,111.4,62.8,24.3,11.6,7.4,16.3,19.4,53.7,...,79.7,143.9,265.6,226.7,179.6,133.2,88.0,43.6,29.5,28.3,19.5,46.9,100.8,132.1,214.1,235.8,177.6,205.1,99.8,54.4,36.3,8.9,12.1,48.3,55.3
oslo-8116,154.9,207.5,350.7,354.2,262.8,297.4,198.2,77.7,44.7,40.1,49.6,48.0,133.8,214.7,233.4,289.7,194.4,184.0,120.3,73.2,32.4,4.5,11.3,38.4,82.8,...,70.7,133.2,212.4,184.3,158.0,138.6,94.7,42.8,10.7,4.0,5.5,22.9,76.4,118.9,221.6,193.5,155.4,181.2,112.0,48.0,7.2,7.6,11.0,31.5,78.0
oslo-8117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,34.7,56.9,47.4,41.8,36.6,28.5,9.9,2.5,1.8,3.1,7.3,16.6,25.0,45.0,36.6,29.5,35.6,17.2,8.8,2.6,5.0,7.6,6.6,13.5
oslo-8119,86.3,109.3,199.2,196.3,158.7,161.1,92.2,39.9,10.0,6.4,18.8,30.9,73.1,115.1,130.2,169.0,139.5,138.2,92.1,49.5,8.3,6.7,13.4,26.0,63.7,...,94.0,139.6,185.8,128.9,106.2,100.8,72.4,60.0,13.8,8.3,13.0,69.1,130.2,144.0,158.2,138.8,126.9,131.2,87.3,37.1,7.6,7.0,9.4,18.1,45.2
oslo-8120,47.4,68.1,147.0,138.2,110.3,89.1,47.3,24.7,3.3,0.8,1.2,15.7,46.6,76.2,86.8,148.2,72.1,62.8,33.0,17.8,0.9,0.3,0.8,12.0,38.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.3,31.0,49.4,38.8,29.5,31.4,16.2,5.7,1.4,0.8,1.6,11.1,15.4,25.2,43.5,37.8,29.2,34.0,18.4,6.8,1.4,1.3,2.3,4.1,14.7
oslo-8122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.5,82.0,77.1,52.4,33.8,9.7,4.0,10.1,27.8,54.3,...,50.1,75.2,101.6,100.2,80.7,83.2,54.6,36.6,9.3,4.8,6.2,23.9,49.2,66.4,106.0,98.5,81.0,98.5,75.7,39.4,6.4,1.9,13.7,21.2,45.4
oslo-8124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8125,65.3,82.1,120.0,135.6,103.4,104.0,60.0,20.5,6.8,2.2,6.3,20.1,54.3,90.6,89.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8126,100.7,123.0,167.4,163.3,147.7,147.3,92.3,36.7,14.7,8.5,10.6,36.4,79.7,120.2,133.8,159.9,128.1,115.9,76.1,44.3,10.1,8.1,17.5,38.3,76.8,...,62.9,104.1,128.9,123.6,104.0,95.5,55.0,29.3,13.6,9.6,9.6,29.3,55.2,79.9,128.3,124.6,101.2,116.2,56.7,28.1,10.6,9.9,12.0,21.8,45.7
oslo-8127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.9,85.4,129.6,107.5,92.7,81.7,57.5,22.0,5.8,5.0,5.2,20.5,46.6,71.0,124.5,111.4,87.5,98.6,47.5,13.7,2.3,2.9,3.0,7.1,30.6
oslo-8128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.5,105.4,152.2,138.3,120.0,114.8,72.5,31.4,5.2,2.0,4.7,35.7,67.9,99.3,173.5,154.9,126.4,143.7,77.4,34.0,2.8,4.6,3.7,17.0,60.1
oslo-8131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.9,78.5,105.7,98.1,80.8,77.9,50.9,25.8,7.5,5.3,7.9,29.8,50.1,71.1,106.2,105.4,83.9,97.1,52.4,25.9,4.3,8.4,10.7,16.7,34.2
oslo-8132,96.7,134.1,228.4,212.3,176.0,190.4,98.1,35.9,14.5,8.0,11.3,33.9,73.1,130.7,142.6,190.8,141.0,155.5,106.3,61.5,17.6,3.9,12.9,31.7,86.1,...,71.4,115.7,169.0,146.0,122.7,105.1,66.2,26.3,8.2,5.6,10.0,29.2,61.0,85.3,138.2,126.4,105.6,114.1,64.1,24.0,5.5,5.9,10.0,18.9,55.4
oslo-8133,113.7,130.6,215.7,253.6,216.5,217.0,128.8,53.2,31.6,15.3,22.3,53.8,109.5,179.5,213.8,196.1,138.6,188.5,109.3,69.7,17.4,7.0,15.3,45.9,109.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oslo-8135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.1,72.6,107.5,87.7,75.5,70.5,57.4,33.5,9.7,8.2,12.2,33.5,51.3,61.8,111.0,95.0,74.7,86.5,51.4,29.5,7.9,12.6,17.9,23.3,46.1
oslo-8137,175.9,208.4,272.1,302.4,249.7,256.7,172.0,36.1,13.3,4.1,4.8,73.7,149.7,220.5,227.1,308.3,230.9,208.8,143.6,86.3,23.3,6.2,25.1,71.7,165.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drammen-6409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.7,9.0,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drammen-6412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.5,64.1,5638.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drammen-6429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.5,13.4,22.0,19.0,14.7,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drammen-6436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.8,84.8,131.5,115.7,70.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
drammen-6442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.3,34.9,51.5,44.3,28.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 8. Relationship to weather
Correlation of `HtTot` with outdoor temperature per building. A strongly negative value is expected (colder, more heat). A value near zero suggests the building is hard to predict from weather alone or the data is broken.

In [20]:
corr = {}
for _, r in target.iterrows():
    df, _ = load(r)
    d = df[df["Tout"] > -100]
    corr[f'{r["city"]}-{r["building_id"]}'] = d["HtTot"].corr(d["Tout"])
pd.Series(corr, name="corr(HtTot, Tout)").round(2).sort_values()

oslo-8132      -0.88
oslo-8116      -0.87
oslo-8131      -0.86
oslo-8105      -0.85
oslo-8128      -0.84
drammen-6429   -0.84
oslo-8103      -0.83
oslo-8127      -0.82
drammen-6436   -0.81
drammen-6442   -0.81
oslo-8126      -0.80
oslo-8113      -0.80
oslo-8121      -0.79
oslo-8122      -0.79
oslo-8133      -0.79
oslo-8108      -0.77
oslo-8091      -0.77
oslo-8137      -0.76
oslo-8096      -0.76
oslo-8119      -0.75
oslo-8094      -0.73
oslo-8106      -0.73
oslo-8114      -0.73
oslo-8117      -0.71
oslo-8124      -0.71
oslo-8120      -0.69
oslo-8107      -0.69
oslo-8092      -0.68
oslo-8125      -0.67
oslo-8095      -0.66
oslo-8102      -0.66
oslo-8104      -0.65
oslo-8110      -0.64
oslo-8093      -0.64
oslo-8135      -0.57
oslo-8109      -0.50
drammen-6409   -0.29
drammen-6412   -0.01
Name: corr(HtTot, Tout), dtype: float64

## 9. Write down your decisions
Fill these in before the preprocessing step.

- Buildings to exclude (id and reason):
- `RH`: drop / keep:
- Gap rule for weather (interpolate up to N hours?):
- Gap rule for `HtTot` (never fill, drop those rows):
- Handling of `HtTot == 0` and flat stretches:
- Train / validation / test split by building (which ids go where):